name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # tous les jours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: kaluminium
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark
      - uses: actions/upload-artifact@v3
        with:
          name: github-snake
          path: output/
